spring:
  application:
    name: codigoalvo-estapar-garage-sim

  datasource:
    url: jdbc:postgresql://localhost:5432/estapar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    org.springframework.orm.jpa: WARN

garage:
  simulator:
    url: http://localhost:3000

pricing:
  rules:
    - threshold: 0.8     # Até 80% da capacidade -> preço base
      multiplier: 1.0
    - threshold: 0.9     # Entre 80% e 90% -> 1.5x
      multiplier: 1.5
    - threshold: 1.0     # Entre 90% e 100% -> 2x
      multiplier: 2.0
