spring:
  application:
    name: codigoalvo-estapar-garage-sim

  datasource:
    url: jdbc:postgresql://localhost:5432/estapar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

server:
  port: 8080
  address: 0.0.0.0

logging:
  level:
    br.com.codigoalvo: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN
    org.springframework.orm.jpa: WARN

api:
  version: '@project.version@'
  debug:
    enabled: false

garage:
  simulator:
    url: http://localhost:3000

pricing:
  rules:
    - threshold: 0.0    # Base (fallback)
      multiplier: 0.9
    - threshold: 0.25   # >=25%
      multiplier: 1.0
    - threshold: 0.5    # >=50%
      multiplier: 1.1
    - threshold: 0.75   # >=75%
      multiplier: 1.25