spring:
  application:
    name: codigoalvo-estapar-garage-sim

  datasource:
    url: jdbc:postgresql://localhost:5432/estapar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
